name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 7.4.2
        arguments: assembleDebug
    - name: List output directory
      run: |
        echo "Listing all directories:"
        find . -type d | sort
        echo "Listing all APK files:"
        find . -name "*.apk" -type f
        echo "Listing build outputs:"
        ls -la build/outputs || echo "build/outputs not found"
        ls -la */build/outputs || echo "*/build/outputs not found"
    - name: Upload APK (if found)
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: |
          **/app-debug.apk
          **/debug/*.apk
        if-no-files-found: warn
